use std::io::Write;
use std::path::Path;

use crate::data::live::DiagnosticsStore;
use crate::sim::SimState;

pub fn export_markdown(
    dir: &Path,
    diagnostics: &DiagnosticsStore,
    state: Option<&SimState>,
    stem: &str,
) -> Result<String, String> {
    let path = dir.join(format!("{stem}.md"));
    let mut f = std::fs::File::create(&path).map_err(|e| format!("create: {e}"))?;

    writeln!(f, "# Phasma Simulation Report\n").map_err(|e| e.to_string())?;
    writeln!(f, "Generated by phasma v{}\n", env!("CARGO_PKG_VERSION"))
        .map_err(|e| e.to_string())?;

    // Final state summary
    if let Some(s) = state {
        writeln!(f, "## Simulation Summary\n").map_err(|e| e.to_string())?;
        writeln!(f, "| Parameter | Value |").map_err(|e| e.to_string())?;
        writeln!(f, "|---|---|").map_err(|e| e.to_string())?;
        writeln!(f, "| Final time | {:.6} / {:.6} |", s.t, s.t_final).map_err(|e| e.to_string())?;
        writeln!(f, "| Steps | {} |", s.step).map_err(|e| e.to_string())?;
        writeln!(f, "| Grid (density) | {}x{} |", s.density_nx, s.density_ny)
            .map_err(|e| e.to_string())?;
        if s.step > 0 && s.step_wall_ms > 0.0 {
            writeln!(f, "| Last step wall time | {:.1} ms |", s.step_wall_ms)
                .map_err(|e| e.to_string())?;
        }
        writeln!(f).map_err(|e| e.to_string())?;

        // Conservation analysis
        writeln!(f, "## Conservation Analysis\n").map_err(|e| e.to_string())?;
        writeln!(f, "| Quantity | Initial | Final | Drift | Status |")
            .map_err(|e| e.to_string())?;
        writeln!(f, "|---|---|---|---|---|").map_err(|e| e.to_string())?;

        let energy_drift = s.energy_drift();
        let energy_status = if energy_drift.abs() < 1e-6 {
            "excellent"
        } else if energy_drift.abs() < 1e-3 {
            "good"
        } else if energy_drift.abs() < 1e-1 {
            "acceptable"
        } else {
            "poor"
        };
        writeln!(
            f,
            "| Energy E | {:.6e} | {:.6e} | {:.2e} | {} |",
            s.initial_energy, s.total_energy, energy_drift, energy_status
        )
        .map_err(|e| e.to_string())?;

        writeln!(f, "| Mass M | — | {:.6e} | — | — |", s.total_mass).map_err(|e| e.to_string())?;
        writeln!(f, "| Casimir C₂ | — | {:.6e} | — | — |", s.casimir_c2)
            .map_err(|e| e.to_string())?;
        writeln!(f, "| Entropy S | — | {:.6e} | — | — |", s.entropy).map_err(|e| e.to_string())?;
        writeln!(f, "| Momentum px | — | {:.6e} | — | — |", s.momentum[0])
            .map_err(|e| e.to_string())?;
        writeln!(f, "| Momentum py | — | {:.6e} | — | — |", s.momentum[1])
            .map_err(|e| e.to_string())?;
        writeln!(f, "| Momentum pz | — | {:.6e} | — | — |", s.momentum[2])
            .map_err(|e| e.to_string())?;
        writeln!(f).map_err(|e| e.to_string())?;

        // Energy components
        writeln!(f, "## Energy Components\n").map_err(|e| e.to_string())?;
        writeln!(f, "| Component | Value |").map_err(|e| e.to_string())?;
        writeln!(f, "|---|---|").map_err(|e| e.to_string())?;
        writeln!(f, "| Kinetic T | {:.6e} |", s.kinetic_energy).map_err(|e| e.to_string())?;
        writeln!(f, "| Potential W | {:.6e} |", s.potential_energy).map_err(|e| e.to_string())?;
        writeln!(f, "| Total E = T + W | {:.6e} |", s.total_energy).map_err(|e| e.to_string())?;
        writeln!(f, "| Virial ratio 2T/\\|W\\| | {:.4} |", s.virial_ratio)
            .map_err(|e| e.to_string())?;
        writeln!(f, "| ρ_max | {:.6e} |", s.max_density).map_err(|e| e.to_string())?;
        writeln!(f).map_err(|e| e.to_string())?;

        // Exit condition
        if let Some(ref reason) = s.exit_reason {
            writeln!(f, "## Exit Condition\n").map_err(|e| e.to_string())?;
            writeln!(f, "Simulation terminated: **{reason}**\n").map_err(|e| e.to_string())?;
        }
    }

    // Diagnostics time series info
    let n_points = diagnostics.total_energy.len();
    writeln!(f, "## Diagnostics Time Series\n").map_err(|e| e.to_string())?;
    writeln!(f, "- {n_points} diagnostic samples recorded").map_err(|e| e.to_string())?;

    if let (Some(e0), Some(ef)) = (
        diagnostics.total_energy.first_value(),
        diagnostics.total_energy.last_value(),
    ) {
        let drift = if e0 != 0.0 { (ef - e0) / e0.abs() } else { 0.0 };
        writeln!(f, "- Energy drift over series: {drift:.2e}").map_err(|e| e.to_string())?;
    }
    if let (Some(m0), Some(mf)) = (
        diagnostics.total_mass.first_value(),
        diagnostics.total_mass.last_value(),
    ) {
        let drift = if m0 != 0.0 { (mf - m0) / m0.abs() } else { 0.0 };
        writeln!(f, "- Mass drift over series: {drift:.2e}").map_err(|e| e.to_string())?;
    }
    writeln!(f).map_err(|e| e.to_string())?;

    // Recommendations
    writeln!(f, "## Recommendations\n").map_err(|e| e.to_string())?;
    if let Some(s) = state {
        let drift = s.energy_drift().abs();
        if drift > 0.1 {
            writeln!(f, "- **Warning**: Large energy drift ({drift:.2e}). Consider increasing resolution or reducing CFL factor.").map_err(|e| e.to_string())?;
        } else if drift > 1e-3 {
            writeln!(f, "- Energy drift ({drift:.2e}) is moderate. Higher resolution may improve conservation.").map_err(|e| e.to_string())?;
        } else {
            writeln!(f, "- Energy conservation is within acceptable bounds.")
                .map_err(|e| e.to_string())?;
        }
        if s.virial_ratio > 0.0 && (s.virial_ratio - 1.0).abs() > 0.2 {
            writeln!(f, "- Virial ratio ({:.3}) deviates from equilibrium (1.0). System may not be relaxed.", s.virial_ratio).map_err(|e| e.to_string())?;
        }
    } else {
        writeln!(f, "- No simulation state available for analysis.").map_err(|e| e.to_string())?;
    }

    Ok(path.display().to_string())
}
